# # Install pre-commit hooks via
# pre-commit install

- repo: local
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ["-i"]

  # prospector: collection of linters
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector

  - id: check-requirements
    name: check requirements files
    language: system
    entry: python -m scripts.check_requirements -v
    files: ^(requirements.*.txt|Pipfile|setup\.json)$
