name: continuous-integration

on: [push, pull_request]

jobs:

  test-package:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install package
        run: |
          which python
          python -m pip install -e .[tests,pre-commit]
          python -m pip freeze

      - name: Run pre-commit
        run:
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

      - name: Run tests
        run: python -m pytest -v
